### ISSUE TITLE
Ground truth for test and seq

### ISSUE THREAD

**Issue by maups** [fMoW/dataset#1]
Hello,

I just downloaded the AWS repository of rgb images (s3://spacenet-dataset/fmow/fmow-rgb/), but unfortunately it does not contain the ground truth data for test and seq folders. Is this information going to be made available soon? I also tried to download the torrent version (https://github.com/fMoW/dataset/raw/master/fMoW-rgb_seqandgt_v1.2.0.torrent), but it currently has no seeds.

Best regards,
Mauricio

**Comment by mukhery** [comment]
Hi Mauricio,

Thanks for bringing this to our attention. We were just informed that the s3://spacenet-dataset/fmow buckets should now be synchronized with our s3://fmow-rgb and s3://fmow-full buckets. A quick `aws s3 ls s3://spacenet-dataset/fmow/fmow-rgb/` shows the groundtruth.tar.bz2 file in there, so you should be good to go.

I also checked our BitTorrent client again and saw that there still is a second client seeding the fMoW-rgb seq and ground truth data. I'm going to close this issue, but perhaps others can open another issue if the torrent isn't working and they'd like to download the data using that method.

Thanks,
Ryan
