### ISSUE TITLE
Torrent Download: No seeds available

### ISSUE THREAD

**Issue by mburges-cvl** [fMoW/dataset#10]
I'm trying to download rgb-trainval, but there are no seeds available and I do not have an AWS account.

**Comment by IvicaObadic** [comment]
I am also trying to download the full-val-sample via bit torrent, but there are also no seeds available for it. Would you be able to fix this?

Thank you in advance!

**Comment by mukhery** [comment]
Unfortunately, I don't have the resources to fix this. We need some generous individual/organization to donate resources and/or download from AWS and seed themselves.

**Comment by mburges-cvl** [comment]
Hello,

so apparently you can download the dataset from AWS without an account using the `--no-sign-request` flag:

`aws s3 cp s3://spacenet-dataset/Hosted-Datasets/fmow/fmow-version/ /path/to/save/folder/ --recursive --no-sign-request`

where you have to change:

`fmow-version  --> RGB or FULL`

and

`/path/to/save/folder/ --> your local storage path`

Hope it helps!
