### ISSUE TITLE
Nonexistent ISO Alpha-3 country codes

### ISSUE THREAD

**Issue by rubencart** [fMoW/dataset#13]
The paper mentions that the metadata includes ISO Alpha-3 country codes (Appendix I). However, the `country_code` field in the metadata json's includes two codes that do not exist as ISO Alpha-3 code: `KO-` and `CA-`.
- `KO-` is not listed as any country code on the ISO website. `KO` is listed as unassigned _Alpha-2 code_: [link](https://www.iso.org/obp/ui/#iso:code:3166:KO). All locations in the fMoW dataset with this country code are in Kosovo. Kosovo does not have its own ISO Alpha-3 code, the correct code is the one for Serbia: `SRB` (just quoting the ISO website). There is an _unofficial_ Alpha-2 code for Kosovo, as described [here](https://en.wikipedia.org/wiki/XK_(user_assigned_code)); `XK`.
- Same for `CA-`, it does not exist as Alpha-3 code. `CA` exists as Alpha-2 code for Canada ([ISO website](https://www.iso.org/obp/ui/#iso:code:3166:CA)), but the fMoW metadata uses the Alpha-3 code `CAN` to refer to Canada. The locations in the fMoW dataset with `CA-` are around the Caspian Sea, both in southern Russia (Dagestan) and Azerbaijan. I don't know why the proper codes, like `RUS` or `AZE` wouldn't be used. Some of these locations are in Azerbaijan's capital, so doesn't seem like disputed territory.

I'm posting this here not to get political but because I think this might be relevant to some people, and it is poorly documented by fMoW. E.g. I was trying to connect the fMoW countries to ISO 3 country codes in a shapefile to do operations with the locations. Please document this properly somewhere :-).

**Comment by mukhery** [comment]
thank you for catching this!
