### ISSUE TITLE
What do box dimensions mean?

### ISSUE THREAD

**Issue by rubencart** [fMoW/dataset#14]
The ground truth metadata json's denote the bounding box dimensions as `'box': [697, 1451, 5720, 2649]`, but not this repository nor the fMoW paper describes what these dimensions mean. You have to search the baseline code and find in [this function](https://github.com/fMoW/baseline/blob/26a59edde8f3a30af50df95c1ceb37f80f70d5ec/code/data_ml_functions/dataFunctions.py#L107) that these represent `[x, y, w, h]` where `[x, y]` are the upper (?) left corner's indices. Other bounding box annotation schemes exist, e.g. see [here](https://albumentations.ai/docs/getting_started/bounding_boxes_augmentation/#different-annotations-formats), so I think this would be something nice to have clearly documented somewhere.

**Comment by bourcierj** [comment]
Hi @rubencart,
You are correct, the order is "left, top, width, height".
I agree on the lack of documentation. Unfortunately this repository does not seem to be maintained anymore.
