### ISSUE TITLE
Ask for FMoW dataset

### ISSUE THREAD

**Issue by Joanna-0421** [fMoW/dataset#15]
When I attempt to download fMoW dataset, I noticed that only torrent files are available on GitHub or AWS. However, upon trying to download the seed file, I found that no user owns any bucket, making it impossible for me to obtain the dataset corresponding to the seed. Could you please provide a more stable download method for us? Thank you very much for your assistance.

**Comment by bourcierj** [comment]
Hi @Joanna-0421,
I haven't tried downloading using torrent files, but you can download the data directly from AWS S3.
If that can help, here is a [script](https://gist.github.com/bourcierj/30f45383ba9a3177c32e2711b2cd05e1) showing how to download the fMoW-RGB dataset (train and val splits only).
