### ISSUE TITLE
md5 hash sums for torrents

### ISSUE THREAD

**Issue by scottlittle** [fMoW/dataset#4]
Could the md5 hash sums for torrents be provided?

**Comment by mukhery** [comment]
I'm not sure I see the point of providing them. The torrent files are small and can be easily re-downloaded if anyone is unsure if they have official versions. (Who checks MD5 sums these days anyways.) Also, if my Github credentials were compromised or someone was performing a MITM then the MD5 sums could be easily compromised as well, so they'd only provide a false sense of security.
