### ISSUE TITLE
downloading via s3

### ISSUE THREAD

**Issue by JonaGanz** [fMoW/dataset#8]
I'm trying to download the data on S3 right now. I have opened an account and installed the command line interface. But I don't get which command I need to download the rgb data.I tried something like:
 `aws s3 cp s3://spacenet-dataset/Hosted-Datasets/fmow/fmow-rgb ./`, but I get an error that the key Hosted-Dataset doesn't exist. I need to download and store the dataset in a specific file.
Thank you in advance.

**Comment by JonaGanz** [comment]
Problem [solved](https://stackoverflow.com/questions/62574538/how-to-download-larg-file-from-aws-s3/62574636#62574636), 

type `aws s3 cp s3://spacenet-dataset/Hosted-Datasets/fmow/fmow-rgb . --recursive` for the whole rgb data. If you want to specify the directory to store the data replace `.` with the desired filename.  Thanks to Chris.

**Comment by kanak8278** [comment]
I have been trying to download the dataset using s3 command. But it says "Access Denied"
`aws s3 cp s3://spacenet-dataset/Hosted-Datasets/fmow/fmow-rgb . --recursive`
`fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied`
